import axios from 'axios'

const topTracksEndpoint = 'https://api.spotify.com/v1/me/top/tracks'
const mock = {
  items: [
    {
      album: {
        album_type: 'SINGLE',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2xsasxj0G1VCLzyX6ygjEC',
            },
            href: 'https://api.spotify.com/v1/artists/2xsasxj0G1VCLzyX6ygjEC',
            id: '2xsasxj0G1VCLzyX6ygjEC',
            name: 'Vega Missile',
            type: 'artist',
            uri: 'spotify:artist:2xsasxj0G1VCLzyX6ygjEC',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/0aABgoF2di43hCtAf2XCA2',
        },
        href: 'https://api.spotify.com/v1/albums/0aABgoF2di43hCtAf2XCA2',
        id: '0aABgoF2di43hCtAf2XCA2',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273071927a304df706d9ccae85a',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02071927a304df706d9ccae85a',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851071927a304df706d9ccae85a',
            width: 64,
          },
        ],
        name: 'Warmongers',
        release_date: '2020-10-23',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:0aABgoF2di43hCtAf2XCA2',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2xsasxj0G1VCLzyX6ygjEC',
          },
          href: 'https://api.spotify.com/v1/artists/2xsasxj0G1VCLzyX6ygjEC',
          id: '2xsasxj0G1VCLzyX6ygjEC',
          name: 'Vega Missile',
          type: 'artist',
          uri: 'spotify:artist:2xsasxj0G1VCLzyX6ygjEC',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 498596,
      explicit: false,
      external_ids: {
        isrc: 'FR9W11934565',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/6l9Ebgt7opzxvsDt8IETJd',
      },
      href: 'https://api.spotify.com/v1/tracks/6l9Ebgt7opzxvsDt8IETJd',
      id: '6l9Ebgt7opzxvsDt8IETJd',
      is_local: false,
      name: 'Warmongers',
      popularity: 38,
      preview_url:
        'https://p.scdn.co/mp3-preview/26bc71b9eefb5badc2b4dcdafe1ce00f85c4ebcf?cid=71a3a5397b9840098bdde0bddd938121',
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:6l9Ebgt7opzxvsDt8IETJd',
    },
    {
      album: {
        album_type: 'SINGLE',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2xsasxj0G1VCLzyX6ygjEC',
            },
            href: 'https://api.spotify.com/v1/artists/2xsasxj0G1VCLzyX6ygjEC',
            id: '2xsasxj0G1VCLzyX6ygjEC',
            name: 'Vega Missile',
            type: 'artist',
            uri: 'spotify:artist:2xsasxj0G1VCLzyX6ygjEC',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/0K0iDBZLM8fxElJQ6A6KFJ',
        },
        href: 'https://api.spotify.com/v1/albums/0K0iDBZLM8fxElJQ6A6KFJ',
        id: '0K0iDBZLM8fxElJQ6A6KFJ',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b27379909067ad5802a8f20cdbc7',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e0279909067ad5802a8f20cdbc7',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d0000485179909067ad5802a8f20cdbc7',
            width: 64,
          },
        ],
        name: 'Expansion',
        release_date: '2020-09-18',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:0K0iDBZLM8fxElJQ6A6KFJ',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2xsasxj0G1VCLzyX6ygjEC',
          },
          href: 'https://api.spotify.com/v1/artists/2xsasxj0G1VCLzyX6ygjEC',
          id: '2xsasxj0G1VCLzyX6ygjEC',
          name: 'Vega Missile',
          type: 'artist',
          uri: 'spotify:artist:2xsasxj0G1VCLzyX6ygjEC',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 311004,
      explicit: false,
      external_ids: {
        isrc: 'FR9W11934561',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/591pnGpkSms2aA1GAU79qC',
      },
      href: 'https://api.spotify.com/v1/tracks/591pnGpkSms2aA1GAU79qC',
      id: '591pnGpkSms2aA1GAU79qC',
      is_local: false,
      name: 'Expansion',
      popularity: 32,
      preview_url:
        'https://p.scdn.co/mp3-preview/7ec58fa81c81600a34c24e7ed6c7fac6b584d560?cid=71a3a5397b9840098bdde0bddd938121',
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:591pnGpkSms2aA1GAU79qC',
    },
    {
      album: {
        album_type: 'ALBUM',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2ZV8HrS6uy7XtfPoUlqdV5',
            },
            href: 'https://api.spotify.com/v1/artists/2ZV8HrS6uy7XtfPoUlqdV5',
            id: '2ZV8HrS6uy7XtfPoUlqdV5',
            name: 'Mauro Bertoli',
            type: 'artist',
            uri: 'spotify:artist:2ZV8HrS6uy7XtfPoUlqdV5',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5KHW83iPshVaMLxGGfkZzc',
        },
        href: 'https://api.spotify.com/v1/albums/5KHW83iPshVaMLxGGfkZzc',
        id: '5KHW83iPshVaMLxGGfkZzc',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b2733d6243605e647869d4e3d670',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e023d6243605e647869d4e3d670',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d000048513d6243605e647869d4e3d670',
            width: 64,
          },
        ],
        name:
          'Debussy: Arabesques - Satie: Gnosiennes - Poulenc: 3 Novelettes - Beethoven: Fur Elise, Bagatelles Op. 126, Rondo Op. 129 - Mendelssohn: Rondo Capriccioso Op. 14 - Brahms: Sonata No. 1 Op. 1',
        release_date: '2016-06-29',
        release_date_precision: 'day',
        total_tracks: 24,
        type: 'album',
        uri: 'spotify:album:5KHW83iPshVaMLxGGfkZzc',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2ZV8HrS6uy7XtfPoUlqdV5',
          },
          href: 'https://api.spotify.com/v1/artists/2ZV8HrS6uy7XtfPoUlqdV5',
          id: '2ZV8HrS6uy7XtfPoUlqdV5',
          name: 'Mauro Bertoli',
          type: 'artist',
          uri: 'spotify:artist:2ZV8HrS6uy7XtfPoUlqdV5',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 290038,
      explicit: false,
      external_ids: {
        isrc: 'ushm21600771',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/1ulHVDFC1wNpbDC2mWE4ZA',
      },
      href: 'https://api.spotify.com/v1/tracks/1ulHVDFC1wNpbDC2mWE4ZA',
      id: '1ulHVDFC1wNpbDC2mWE4ZA',
      is_local: false,
      name: 'Deux arabesques, L. 66: 1. Andantino con moto',
      popularity: 6,
      preview_url:
        'https://p.scdn.co/mp3-preview/79c18d65ac6a94b658005d95cd2c48e778831ad0?cid=71a3a5397b9840098bdde0bddd938121',
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:1ulHVDFC1wNpbDC2mWE4ZA',
    },
    {
      album: {
        album_type: 'SINGLE',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5dH56mquzTg0L5qjmeiUqf',
            },
            href: 'https://api.spotify.com/v1/artists/5dH56mquzTg0L5qjmeiUqf',
            id: '5dH56mquzTg0L5qjmeiUqf',
            name: 'TODIIX',
            type: 'artist',
            uri: 'spotify:artist:5dH56mquzTg0L5qjmeiUqf',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/195XoN46gXi7yuYTACzoeG',
        },
        href: 'https://api.spotify.com/v1/albums/195XoN46gXi7yuYTACzoeG',
        id: '195XoN46gXi7yuYTACzoeG',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b27332e00747d0eef887c2412752',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e0232e00747d0eef887c2412752',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d0000485132e00747d0eef887c2412752',
            width: 64,
          },
        ],
        name: 'Feel My Love',
        release_date: '2020-10-09',
        release_date_precision: 'day',
        total_tracks: 1,
        type: 'album',
        uri: 'spotify:album:195XoN46gXi7yuYTACzoeG',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/5dH56mquzTg0L5qjmeiUqf',
          },
          href: 'https://api.spotify.com/v1/artists/5dH56mquzTg0L5qjmeiUqf',
          id: '5dH56mquzTg0L5qjmeiUqf',
          name: 'TODIIX',
          type: 'artist',
          uri: 'spotify:artist:5dH56mquzTg0L5qjmeiUqf',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 190673,
      explicit: false,
      external_ids: {
        isrc: 'NL1AP2090331',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/3IpPZ6QYc9nGGihOKVWWMN',
      },
      href: 'https://api.spotify.com/v1/tracks/3IpPZ6QYc9nGGihOKVWWMN',
      id: '3IpPZ6QYc9nGGihOKVWWMN',
      is_local: false,
      name: 'Feel My Love',
      popularity: 29,
      preview_url:
        'https://p.scdn.co/mp3-preview/375ca01845b407a6fb84cbc63f580ec6f8c23c3b?cid=71a3a5397b9840098bdde0bddd938121',
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:3IpPZ6QYc9nGGihOKVWWMN',
    },
    {
      album: {
        album_type: 'SINGLE',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/5D4cdVgjT4jAN2IDrV7mVe',
            },
            href: 'https://api.spotify.com/v1/artists/5D4cdVgjT4jAN2IDrV7mVe',
            id: '5D4cdVgjT4jAN2IDrV7mVe',
            name: 'Luca Draccar',
            type: 'artist',
            uri: 'spotify:artist:5D4cdVgjT4jAN2IDrV7mVe',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/0MIEXYVsnKGy7iBwSuzGUU',
        },
        href: 'https://api.spotify.com/v1/albums/0MIEXYVsnKGy7iBwSuzGUU',
        id: '0MIEXYVsnKGy7iBwSuzGUU',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273539a41f90beaf94c6f82d4c9',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02539a41f90beaf94c6f82d4c9',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851539a41f90beaf94c6f82d4c9',
            width: 64,
          },
        ],
        name: 'Flamboyant',
        release_date: '2020-08-28',
        release_date_precision: 'day',
        total_tracks: 4,
        type: 'album',
        uri: 'spotify:album:0MIEXYVsnKGy7iBwSuzGUU',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/5D4cdVgjT4jAN2IDrV7mVe',
          },
          href: 'https://api.spotify.com/v1/artists/5D4cdVgjT4jAN2IDrV7mVe',
          id: '5D4cdVgjT4jAN2IDrV7mVe',
          name: 'Luca Draccar',
          type: 'artist',
          uri: 'spotify:artist:5D4cdVgjT4jAN2IDrV7mVe',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 646125,
      explicit: false,
      external_ids: {
        isrc: 'FR96X2087805',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/1lHvMGnvWGhYQltRgXDbYM',
      },
      href: 'https://api.spotify.com/v1/tracks/1lHvMGnvWGhYQltRgXDbYM',
      id: '1lHvMGnvWGhYQltRgXDbYM',
      is_local: false,
      name: 'Birba',
      popularity: 42,
      preview_url:
        'https://p.scdn.co/mp3-preview/cbe484dd7c5b555fa84d4a7ac429ff3ddbd314e1?cid=71a3a5397b9840098bdde0bddd938121',
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:1lHvMGnvWGhYQltRgXDbYM',
    },
    {
      album: {
        album_type: 'SINGLE',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/6dC41opH96WjFwWhhAxBsS',
            },
            href: 'https://api.spotify.com/v1/artists/6dC41opH96WjFwWhhAxBsS',
            id: '6dC41opH96WjFwWhhAxBsS',
            name: 'Helsloot',
            type: 'artist',
            uri: 'spotify:artist:6dC41opH96WjFwWhhAxBsS',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/5zY9TsJnvsXb5VMTjH7RPu',
        },
        href: 'https://api.spotify.com/v1/albums/5zY9TsJnvsXb5VMTjH7RPu',
        id: '5zY9TsJnvsXb5VMTjH7RPu',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273510e0ba4ca7867fecad21f54',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02510e0ba4ca7867fecad21f54',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851510e0ba4ca7867fecad21f54',
            width: 64,
          },
        ],
        name: 'Belfort',
        release_date: '2020-10-16',
        release_date_precision: 'day',
        total_tracks: 2,
        type: 'album',
        uri: 'spotify:album:5zY9TsJnvsXb5VMTjH7RPu',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/6dC41opH96WjFwWhhAxBsS',
          },
          href: 'https://api.spotify.com/v1/artists/6dC41opH96WjFwWhhAxBsS',
          id: '6dC41opH96WjFwWhhAxBsS',
          name: 'Helsloot',
          type: 'artist',
          uri: 'spotify:artist:6dC41opH96WjFwWhhAxBsS',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 371612,
      explicit: false,
      external_ids: {
        isrc: 'DEBE72000385',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/6ESEOwrbLFiMrPbf7KO9lN',
      },
      href: 'https://api.spotify.com/v1/tracks/6ESEOwrbLFiMrPbf7KO9lN',
      id: '6ESEOwrbLFiMrPbf7KO9lN',
      is_local: false,
      name: 'Belfort',
      popularity: 25,
      preview_url:
        'https://p.scdn.co/mp3-preview/72febd58510d9863e43941efff81cbfd648063df?cid=71a3a5397b9840098bdde0bddd938121',
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:6ESEOwrbLFiMrPbf7KO9lN',
    },
    {
      album: {
        album_type: 'SINGLE',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/0dmK5swyEcHMHK570klgLx',
            },
            href: 'https://api.spotify.com/v1/artists/0dmK5swyEcHMHK570klgLx',
            id: '0dmK5swyEcHMHK570klgLx',
            name: 'Gabriel Marchisio',
            type: 'artist',
            uri: 'spotify:artist:0dmK5swyEcHMHK570klgLx',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/6pBOIrH4vdpwatqzBf70ix',
        },
        href: 'https://api.spotify.com/v1/albums/6pBOIrH4vdpwatqzBf70ix',
        id: '6pBOIrH4vdpwatqzBf70ix',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273d4852f0f6c6fdbdc33efc397',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02d4852f0f6c6fdbdc33efc397',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851d4852f0f6c6fdbdc33efc397',
            width: 64,
          },
        ],
        name: 'More Days on Week',
        release_date: '2011',
        release_date_precision: 'year',
        total_tracks: 2,
        type: 'album',
        uri: 'spotify:album:6pBOIrH4vdpwatqzBf70ix',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/0dmK5swyEcHMHK570klgLx',
          },
          href: 'https://api.spotify.com/v1/artists/0dmK5swyEcHMHK570klgLx',
          id: '0dmK5swyEcHMHK570klgLx',
          name: 'Gabriel Marchisio',
          type: 'artist',
          uri: 'spotify:artist:0dmK5swyEcHMHK570klgLx',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 494813,
      explicit: false,
      external_ids: {
        isrc: 'BGA471515554',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/3kn0wJavHokxqS65gkj44N',
      },
      href: 'https://api.spotify.com/v1/tracks/3kn0wJavHokxqS65gkj44N',
      id: '3kn0wJavHokxqS65gkj44N',
      is_local: false,
      name: 'More Days on Week',
      popularity: 27,
      preview_url:
        'https://p.scdn.co/mp3-preview/b66aeda1bffcdbb614c291f76873ff14b4229257?cid=71a3a5397b9840098bdde0bddd938121',
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:3kn0wJavHokxqS65gkj44N',
    },
    {
      album: {
        album_type: 'ALBUM',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/4gwpcMTbLWtBUlOijbVpuu',
            },
            href: 'https://api.spotify.com/v1/artists/4gwpcMTbLWtBUlOijbVpuu',
            id: '4gwpcMTbLWtBUlOijbVpuu',
            name: 'Capital Cities',
            type: 'artist',
            uri: 'spotify:artist:4gwpcMTbLWtBUlOijbVpuu',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/3WrufJir7I61NkvkDwxero',
        },
        href: 'https://api.spotify.com/v1/albums/3WrufJir7I61NkvkDwxero',
        id: '3WrufJir7I61NkvkDwxero',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b27313c6cb6a81c8db4dbc8b9924',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e0213c6cb6a81c8db4dbc8b9924',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d0000485113c6cb6a81c8db4dbc8b9924',
            width: 64,
          },
        ],
        name: 'In A Tidal Wave Of Mystery (Deluxe Edition)',
        release_date: '2013',
        release_date_precision: 'year',
        total_tracks: 16,
        type: 'album',
        uri: 'spotify:album:3WrufJir7I61NkvkDwxero',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/4gwpcMTbLWtBUlOijbVpuu',
          },
          href: 'https://api.spotify.com/v1/artists/4gwpcMTbLWtBUlOijbVpuu',
          id: '4gwpcMTbLWtBUlOijbVpuu',
          name: 'Capital Cities',
          type: 'artist',
          uri: 'spotify:artist:4gwpcMTbLWtBUlOijbVpuu',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 192789,
      explicit: false,
      external_ids: {
        isrc: 'USCA21203108',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/6Z8R6UsFuGXGtiIxiD8ISb',
      },
      href: 'https://api.spotify.com/v1/tracks/6Z8R6UsFuGXGtiIxiD8ISb',
      id: '6Z8R6UsFuGXGtiIxiD8ISb',
      is_local: false,
      name: 'Safe And Sound',
      popularity: 82,
      preview_url: null,
      track_number: 1,
      type: 'track',
      uri: 'spotify:track:6Z8R6UsFuGXGtiIxiD8ISb',
    },
    {
      album: {
        album_type: 'ALBUM',
        artists: [
          {
            external_urls: {
              spotify: 'https://open.spotify.com/artist/2pHk4wAmL7ofTAuvCIUWtv',
            },
            href: 'https://api.spotify.com/v1/artists/2pHk4wAmL7ofTAuvCIUWtv',
            id: '2pHk4wAmL7ofTAuvCIUWtv',
            name: 'Roméo Elvis',
            type: 'artist',
            uri: 'spotify:artist:2pHk4wAmL7ofTAuvCIUWtv',
          },
        ],
        available_markets: [
          'AD',
          'AE',
          'AR',
          'AT',
          'AU',
          'BE',
          'BG',
          'BH',
          'BO',
          'BR',
          'CA',
          'CH',
          'CL',
          'CO',
          'CR',
          'CY',
          'CZ',
          'DE',
          'DK',
          'DO',
          'DZ',
          'EC',
          'EE',
          'EG',
          'ES',
          'FI',
          'FR',
          'GB',
          'GR',
          'GT',
          'HK',
          'HN',
          'HU',
          'ID',
          'IE',
          'IL',
          'IN',
          'IS',
          'IT',
          'JO',
          'JP',
          'KW',
          'LB',
          'LI',
          'LT',
          'LU',
          'LV',
          'MA',
          'MC',
          'MT',
          'MX',
          'MY',
          'NI',
          'NL',
          'NO',
          'NZ',
          'OM',
          'PA',
          'PE',
          'PH',
          'PL',
          'PS',
          'PT',
          'PY',
          'QA',
          'RO',
          'SA',
          'SE',
          'SG',
          'SK',
          'SV',
          'TH',
          'TN',
          'TR',
          'TW',
          'US',
          'UY',
          'VN',
          'ZA',
        ],
        external_urls: {
          spotify: 'https://open.spotify.com/album/6hIAy4WsqxwWnGvZYdjnHO',
        },
        href: 'https://api.spotify.com/v1/albums/6hIAy4WsqxwWnGvZYdjnHO',
        id: '6hIAy4WsqxwWnGvZYdjnHO',
        images: [
          {
            height: 640,
            url:
              'https://i.scdn.co/image/ab67616d0000b273f99fb4c3e3812bb4ea81f1f7',
            width: 640,
          },
          {
            height: 300,
            url:
              'https://i.scdn.co/image/ab67616d00001e02f99fb4c3e3812bb4ea81f1f7',
            width: 300,
          },
          {
            height: 64,
            url:
              'https://i.scdn.co/image/ab67616d00004851f99fb4c3e3812bb4ea81f1f7',
            width: 64,
          },
        ],
        name: 'Chocolat',
        release_date: '2019-04-12',
        release_date_precision: 'day',
        total_tracks: 19,
        type: 'album',
        uri: 'spotify:album:6hIAy4WsqxwWnGvZYdjnHO',
      },
      artists: [
        {
          external_urls: {
            spotify: 'https://open.spotify.com/artist/2pHk4wAmL7ofTAuvCIUWtv',
          },
          href: 'https://api.spotify.com/v1/artists/2pHk4wAmL7ofTAuvCIUWtv',
          id: '2pHk4wAmL7ofTAuvCIUWtv',
          name: 'Roméo Elvis',
          type: 'artist',
          uri: 'spotify:artist:2pHk4wAmL7ofTAuvCIUWtv',
        },
      ],
      available_markets: [
        'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IN',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA',
      ],
      disc_number: 1,
      duration_ms: 192000,
      explicit: true,
      external_ids: {
        isrc: 'BE5EO1900005',
      },
      external_urls: {
        spotify: 'https://open.spotify.com/track/4RpNETpCJm2Nfr3aTpt4cJ',
      },
      href: 'https://api.spotify.com/v1/tracks/4RpNETpCJm2Nfr3aTpt4cJ',
      id: '4RpNETpCJm2Nfr3aTpt4cJ',
      is_local: false,
      name: 'Coeur des hommes',
      popularity: 47,
      preview_url: null,
      track_number: 4,
      type: 'track',
      uri: 'spotify:track:4RpNETpCJm2Nfr3aTpt4cJ',
    },
  ],
  total: 9,
  limit: 20,
  offset: 0,
  href: 'https://api.spotify.com/v1/me/top/tracks',
  previous: null,
  next: null,
}

class SpotifyService {
  static getTopTrack(token) {
    console.log('SpotifyService | getTopTrack')
    console.log('topTracksEndpoint:', topTracksEndpoint)
    console.log('token:', token)
    return new Promise((resolve, reject) => {
      axios
        .get(topTracksEndpoint, {
          headers: {
            authorization: 'Bearer ' + token,
            'content-type': 'application/json',
          },
        })
        .then((res) => {
          // console.log(res.data)
          const items = res.data.items
          resolve(
            items.map((item) => ({
              id: item.id,
              name: item.name,
              artists: item.artists.map((artist) => artist.name),
              release_date: item.release_date,
              popularity: item.popularity,
              image: item.album.images[item.album.images.length - 1].url,
            }))
          )
        })
        .catch((err) => {
          console.log('err:', err)
          // reject(err)
          resolve([])
        })
    })
  }

  static getMock(token) {
    console.log('SpotifyService | getMock')
    // console.log('token:', token)
    return new Promise((resolve, reject) => {
      const items = mock.items
      resolve(
        items.map((item) => ({
          id: item.id,
          name: item.name,
          artists: item.artists.map((artist) => artist.name),
          release_date: item.release_date,
          popularity: item.popularity,
          image: item.album.images[item.album.images.length - 1].url,
        }))
      )
    })
  }
}

export default SpotifyService
